############################################
# version : rocketmq-console:1.0.0
# desc : 安装rocketmq consule
############################################
# 设置继承自centos ssh ,java版本镜像
FROM 10.4.65.226/linux/centos:ssh-7

# 下面是一些创建者的基本信息
MAINTAINER wangwei (www6v@126.com)

#安装console
RUN wget http://10.4.65.35:8080/hdpSoftware/rocketmq-console-ng-1.0.0.jar && mv rocketmq-console-ng-1.0.0.jar /usr/local/app.jar



