version: '2'

services:
  hadoop-slave1:
     image: 10.4.65.226/deeplearning/hadoop:2.7.3v2
     container_name: hadoop-slave1
     hostname: hadoop-slave1
     volumes:
       - ./hadoop/conf:/usr/local/hadoop/etc/hadoop
       - ./hadoop/slave/data1:/works/dfs/data
       - /etc/localtime:/etc/localtime:ro
     networks:
            - hdpOverlay
     ports:
        - "10025:22"
  hadoop-slave2:
     image: 10.4.65.226/deeplearning/hadoop:2.7.3v2
     container_name: hadoop-slave2
     hostname: hadoop-slave2
     volumes:
       - ./hadoop/conf:/usr/local/hadoop/etc/hadoop
       - ./hadoop/slave/data2:/works/dfs/data
       - /etc/localtime:/etc/localtime:ro
     networks:
             - hdpOverlay
     ports:
        - "10024:22"
  hadoop-slave3:
     image: 10.4.65.226/deeplearning/hadoop:2.7.3v2
     container_name: hadoop-slave3
     hostname: hadoop-slave3
     volumes:
         - ./hadoop/conf:/usr/local/hadoop/etc/hadoop
         - ./hadoop/slave/data3:/works/dfs/data
         - /etc/localtime:/etc/localtime:ro
     networks:
             - hdpOverlay
     ports:
          - "10023:22"
  hadoop-master:
     image: 10.4.65.226/deeplearning/hadoop:2.7.3v2
     container_name: hadoop-master
     hostname: hadoop-master
     volumes:
       - ./hadoop/conf:/usr/local/hadoop/etc/hadoop
       - ./hadoop/master/name:/works/dfs/name
       - ./hadoop/master/namesecondary:/works/dfs/namesecondary
       - /etc/localtime:/etc/localtime:ro
     networks:
            - hdpOverlay
     ports:
       - "8070:50070"
       - "8090:50090"
       - "8075:50075"
       - "8888:19888"
       - "8042:8042"
       - "10022:22"
       - "8088:8088"
     links:
       - hadoop-slave1
       - hadoop-slave2
       - hadoop-slave3
networks:
  hdpOverlay:
    external: true