version: '2'

services:
    postgresql-imgslmr:
        container_name: postgresql-imgslmr
        hostname: postgresql-imgslmr
        image: 10.4.65.226/library/postgres:imgsmlr-9.5.6
        ports:
            - '5432:5432'
        volumes:
            - ./imagesearch/postgresql/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
        networks:
            - hdpOverlay

networks:
  hdpOverlay:
    external: true